# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Data Archive | Doyle
email: skadudd13@gmail.com
author: Doyle
description: > # this means to ignore newlines until "baseurl:"
  데이터 분석의 정수리
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://skadudd.github.io" # the base hostname & protocol for your site
lang: ko_KR

# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
permalink: /articles/:year/:month/:day/:title

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 5
paginate_path: '/page/:num/'

defaults:
  -
    scope:
      path: "assets/**/*.pdf"
    values:
      sitemap: false